### PR TITLE
jan4x4 v1.0.1

### PR DESCRIPTION
**Pull request by BnjmnZmmrmn**
**contents**
- jan4x4 in GamesmanClassic

**refs**
- [design doc](https://docs.google.com/document/d/1MkRzA-rv7JFlD2CS-moxAVlmknuRZmRLR1QojqdEJS8/edit?tab=t.0)
- [v1.0.0 attempt](https://github.com/GamesCrafters/GamesmanClassic/pull/65)

**reviewer notes**
during our last demo, we faced a few issues:
- incorrect state values
- `PrintPosition` was ugly

here is new win values after fixing bug in `Primitive` (thanks @AndyKim519)
``` Remoteness          Win         Lose          Tie         Draw        Total
        ------------------------------------------------------------------------------
               Inf            0            0            0            0            0
                31            0            0         2600            0         2600
                22            0           16            0            0           16
                21           16            0            0            0           16
                20            0           64            0            0           64
                19          256            0            0            0          256
                18            0          336            0            0          336
                17          428            0            0            0          428
                16            0          400            0            0          400
                15          352            0            0            0          352
                14            0          682            0            0          682
                13          622            0            0            0          622
                12            0         1246            0            0         1246
                11         1296            0            0            0         1296
                10            0         2372            0            0         2372
                 9         2378            0            0            0         2378
                 8            0         4528            0            0         4528
                 7         5716            0            0            0         5716
                 6            0        11182            0            0        11182
                 5        20948            0            0            0        20948
                 4            0        39355            0            0        39355
                 3       100745            0            0            0       100745
                 2            0       117516            0            0       117516
                 1       312696            0            0            0       312696
                 0            0       125164            0            0       125164
        ------------------------------------------------------------------------------
        Totals           445453       302861         2600            0       750914
```

here is new `PrintPosition` with legend and better move strings (thanks @ajdema)
``` 
         (  1  2  3  4 )           : b w b w
         (  5  6  7  8 )           : - - - -
LEGEND:  (  9 10 11 12 )   TOTAL:  : - - - -
         ( 13 14 15 16 )           : w b w b (Player should Draw-Draw in 31)

  Player's move:

Valid Moves: [14 10] [12 8] [3 7] [1 5]
```

### CODE REVIEW

**Comment by BnjmnZmmrmn** [comment]
for some reason cannot at @AndyKim519 as reviewer. is he in github org?

**Review by ajdema — APPROVED** [review]
Looks Great

**Comment by BnjmnZmmrmn** [comment]
@ajdema please make 1 indexed :)

**Comment by BnjmnZmmrmn** [comment]
@ajdema nice, thank you! description updated

**Pull request closed without merging**
